### ISSUE TITLE
[Bug] Most recent 1.20.1 build compiled with wrong java version (1.0.7)

### ISSUE THREAD

**Issue by Fealtous** [Stereowalker/Reforged#134]
Looks like you didn't change the java version back before building after backporting your 1.20.6 changes. Hopefully caught this soon enough so there aren't _too_ many bug reports. [Log](https://gnomebot.dev/paste/mclogs/huCmmLk)

**Comment by Stereowalker** [comment]
Ah, my bad. I forgot to do that

**Comment by Stereowalker** [comment]
Lol, I fixed it for forge but forgot about fabric

**Comment by Stereowalker** [comment]
And it's been fixed. I re-uploaded it. Thanks for pointing it out

**Comment by QianFuv** [comment]
@Stereowalker I apologize for the inconvenience. I have tried the latest version of Reforged (1.20.1 forge) on CurseForge and Modrinth, but they still throw the same error mentioned in the issue when launching.

**Comment by QianFuv** [comment]
Further information: After testing unionlib (UnionLib-1.20.1-12.0.12-Forge-all.jar), I encountered an mixin failure issue on 1.20.1 Forge, which causes the game to crash even without reforged.
Log: [Same to origin issue](https://mclo.gs/ohbfcxA)

**Comment by Stereowalker** [comment]
@QianFuv Update UnionLib to 12.0.13. I've included the refkap file

**Comment by QianFuv** [comment]
@Stereowalker Still have some issue with mixin.
Log: https://mclo.gs/dbhxH83
