### ISSUE TITLE
Game Crashing when trying to use anvil to upgrade item (Version: 1.20.1-6.0.8-Forge)

### ISSUE THREAD

**Issue by propel007** [Stereowalker/Reforged#149]
@Stereowalker 
Im playing a modpack [Abyssal Ascent](https://www.curseforge.com/minecraft/modpacks/abyssal-ascent) with Reforged (formerly Tiered) to use the Armorer's hammer to repair Utherium Armor (from The Undergarden mod). Anvil works otherwise. 

Thread: Render thread
Suspected Mod: 
	Tiered (tiered), Version: 1.20.1-6.0.8-Forge
		Issue tracker URL: https://github.com/Stereowalker/tiered/issues
		Mixin class: com.stereowalker.tiered.mixin.AnvilMenuMixin
		Target: net.minecraft.world.inventory.AnvilMenu

https://pastes.dev/bOU1IlKUme

I know this could be an issue with a seprate mod considering modpacks always have compatability issues, but is there anything you see in my crash file that you see as suspicious?

**Comment by DonatoDeluxe** [comment]
The same happens on my server. Modpack runs fine except for this event.
As soon as i try to take out the item from the output (right side of anvil) it crashes:

<img width="1073" height="713" alt="Image" src="https://github.com/user-attachments/assets/136d0caa-ea29-4ed1-8b8d-4ee5094c6b41" />

[crash-2025-09-17_20.35.16-client.txt](https://github.com/user-attachments/files/22392219/crash-2025-09-17_20.35.16-client.txt)

Can someone help?

Thank you in advance

**Comment by KnightofStress** [comment]
I am having the same issue as OP with some of the Iron's armors
java.lang.NullPointerException: Cannot invoke "com.stereowalker.tiered.api.PotentialAttribute.getReforgeItem()" because "reforgedAttribute" is null

**Comment by wforte4** [comment]
I am also experiencing this issue. Getting the same error as KnightofStress

**Comment by Stereowalker** [comment]
Should be fixed in 1.0.10

**Comment by FFGFlash** [comment]
> Should be fixed in 1.0.10

I've updated to 1.0.10, it's still crashing putting any tools and armor from The Undergarden in the anvil. At least I haven't experienced the issue with any other modded or vanilla tools/armor.

[Crash Report](https://pastes.dev/3vCrSdb8c1)

[Latest Log](https://pastes.dev/7wGRvgHtk2)
